import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { PLATFORM_REGISTRY } from "../platforms/registry.ts";

export const LIBRARY_README = `# dev-library

Place your own legally obtained ROMs in the matching platform folder

Files generated by \`pnpm fixtures\` are not playable. They exist to test the
the scanner: filename parsing, platform aliases, and missing-file handling.
Each starts with a SAVESLOT-FIXTURE-V1 header so the scanner can recognise them.

Set ALLOW_FAKE_ROM_FIXTURES=true in .env.local to have them appear in the
catalogue. With it false, the scanner skips them.

bios/ is reserved and never scanned for games.
`;

export async function ensureLibraryLayout(root: string): Promise<void> {
    await mkdir(root, { recursive: true });
    for (const platform of PLATFORM_REGISTRY) {
        await mkdir(path.join(root, platform.slug), { recursive: true });
    }
    await mkdir(path.join(root, "bios"), { recursive: true });
    await writeFile(path.join(root, "README.md"), LIBRARY_README);
}

export async function ensureDataLayout(root: string): Promise<void> {
    for (const directory of ["", "temp", "logs", "backups", "artwork", "saves", "states"]) {
        await mkdir(path.join(root, directory), { recursive: true });
    }
}