import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { parseArgs } from "node:util";
import { env } from "../lib/config/env.ts";
import { fixtureContent, isFixtureFile } from "../lib/scanning/fixtures.ts";

const FIXTURES: Array<[platform: string, files: string[]]> = [
    [
        "nes",
        [
            "Contra (USA).nes",
            "Legend of Zelda, The (USA) (Rev 1).nes",
            "Mega Man 2 (Special Edition) (Japan).nes",
        ],
    ],
    [
        "snes",
        ["Chrono Trigger (USA).sfc", "Super Mario World (USA, Europe).smc"],
    ],
    ["gb", ["Tetris (World).gb"]],
    ["gbc", ["Pokemon Crystal (USA, Europe) (En,Fr,De).gbc"]],
    ["gba", ["Metroid Fusion (USA) [!].gba"]],
    ["mastersystem", ["Alex Kidd in Miracle World (Europe).sms"]],
    ["genesis", ["Sonic the Hedgehog (World).md"]],
    ["gamegear", ["Sonic Chaos (Europe).gg"]],
    ["n64", ["Super Mario 64 (USA) (Rev A).z64"]],
];

const README = `# dev-library

Place your own legally obtained ROMs in the matching platform folder

Files generated by \`pnpm fixtures\` are not playable. They exist to test the
the scanner: filename parsing, platform aliases, and missing-file handling.
Each starts with a SAVESLOT-FIXTURE-V1 header so the scanner can recognise them.

Set ALLOW_FAKE_ROM_FIXTURES=true in .env.local to have them appear in the
catalogue. With it false, the scanner skips them.
`;

async function removeFixtures(root: string): Promise<number> {
    let removed = 0;
    for (const [platform] of FIXTURES) {
        const directory = path.join(root, platform);
        let entries: string[];
        try {
            entries = await readdir(directory);
        } catch {
            continue;
        }
        for (const name of entries) {
            const file = path.join(directory, name);
            if (await isFixtureFile(file)) {
                await rm(file, { force: true });
                removed += 1;
            }
        }
    }
    return removed;
}

async function main(): Promise<number> {
    const { values } = parseArgs({
        options: {
            clean: { type: "boolean", default: false },
            help: { type: "boolean", short: "h", default: false },
        },
    });
    if (values.help) {
        console.log(
            [
                "Usage: pnpm fixtures [--clean]",
                "",
                "Writes non-playable scanner fixtures into the library.",
                "--clean removes them again, leaving real ROMs untouched.",
            ].join("\n"),
        );
        return 0;
    }
    const root = env.romLibraryPath;
    await mkdir(root, { recursive: true });
    await writeFile(path.join(root, "README.md"), README);
    if (values.clean) {
        const removed = await removeFixtures(root);
        console.log(`Removed ${removed} fixture${removed === 1 ? "" : "s"}.`);
        return 0;
    }
    let written = 0;
    let skipped = 0;
    for (const [platform, files] of FIXTURES) {
        const directory = path.join(root, platform);
        await mkdir(directory, { recursive: true });
        for (const name of files) {
            const file = path.join(directory, name);
            const exists = await isFixtureFile(file).catch(() => false);
            if (!exists) {
                try {
                    await writeFile(file, fixtureContent(name), { flag: "wx" });
                    written += 1;
                    continue;
                } catch {
                    skipped += 1;
                    continue;
                }
            }
            await writeFile(file, fixtureContent(name));
            written += 1;
        }
    }
    console.log(`Wrote ${written} fixtures into ${env.ROM_LIBRARY_PATH}`);
    if (skipped > 0) {
        console.warn(`Skipped ${skipped} existing non-fixture file(s).`);
    }
    console.log("These are not playable. Run `pnpm scan --mode quick` to index them.");
    return 0;
}
process.exit(await main());